version: '3.7'

services:
  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: monika1407
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    command: ["--local-infile"]
    volumes:
      - /workspace/sql_db/mysql:/etc/mysql/conf.d


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: monika1407
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - /workspace/sql_db/config.inc.php:/config.inc.php
      
