version: '3.7'

services:
  mysql:
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: monika1407
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: monika1407
      APACHE_SERVER_NAME: localhost

    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app_network
    volumes:
    - ./logs:/var/log/apache2

networks:
  app_network:
    driver: bridge
